// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userdata.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using scg = global::System.Collections.Generic;
namespace Game.Message {

  #region Messages
  /// <summary>
  ///用户数据
  /// </summary>
  public sealed class UserData : pb::IMessage {
    private static readonly pb::MessageParser<UserData> _parser = new pb::MessageParser<UserData>(() => new UserData());
    public static pb::MessageParser<UserData> Parser { get { return _parser; } }

    private bool isPlaying_;
    public bool IsPlaying {
      get { return isPlaying_; }
      set {
        isPlaying_ = value;
      }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (IsPlaying != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsPlaying);
      }
    }

    public int CalculateSize() {
      int size = 0;
      if (IsPlaying != false) {
        size += 1 + 1;
      }
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            IsPlaying = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///游戏基础数据
  /// </summary>
  public sealed class BaseGameData : pb::IMessage {
    private static readonly pb::MessageParser<BaseGameData> _parser = new pb::MessageParser<BaseGameData>(() => new BaseGameData());
    public static pb::MessageParser<BaseGameData> Parser { get { return _parser; } }

    private int currentLevel_;
    public int CurrentLevel {
      get { return currentLevel_; }
      set {
        currentLevel_ = value;
      }
    }

    private bool isViewPreviousPlot_;
    public bool IsViewPreviousPlot {
      get { return isViewPreviousPlot_; }
      set {
        isViewPreviousPlot_ = value;
      }
    }

    private bool isPlaying_;
    public bool IsPlaying {
      get { return isPlaying_; }
      set {
        isPlaying_ = value;
      }
    }

    private int playNum_;
    public int PlayNum {
      get { return playNum_; }
      set {
        playNum_ = value;
      }
    }

    private static readonly pb::FieldCodec<int> _repeated_getScoreScene_codec
        = pb::FieldCodec.ForInt32(42);
    private readonly pbc::RepeatedField<int> getScoreScene_ = new pbc::RepeatedField<int>();
    public pbc::RepeatedField<int> GetScoreScene {
      get { return getScoreScene_; }
    }

    public void WriteTo(pb::CodedOutputStream output) {
      if (CurrentLevel != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(CurrentLevel);
      }
      if (IsViewPreviousPlot != false) {
        output.WriteRawTag(16);
        output.WriteBool(IsViewPreviousPlot);
      }
      if (IsPlaying != false) {
        output.WriteRawTag(24);
        output.WriteBool(IsPlaying);
      }
      if (PlayNum != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PlayNum);
      }
      getScoreScene_.WriteTo(output, _repeated_getScoreScene_codec);
    }

    public int CalculateSize() {
      int size = 0;
      if (CurrentLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CurrentLevel);
      }
      if (IsViewPreviousPlot != false) {
        size += 1 + 1;
      }
      if (IsPlaying != false) {
        size += 1 + 1;
      }
      if (PlayNum != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PlayNum);
      }
      size += getScoreScene_.CalculateSize(_repeated_getScoreScene_codec);
      return size;
    }

    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            CurrentLevel = input.ReadInt32();
            break;
          }
          case 16: {
            IsViewPreviousPlot = input.ReadBool();
            break;
          }
          case 24: {
            IsPlaying = input.ReadBool();
            break;
          }
          case 32: {
            PlayNum = input.ReadInt32();
            break;
          }
          case 42:
          case 40: {
            getScoreScene_.AddEntriesFrom(input, _repeated_getScoreScene_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
